# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugzilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugzilla',
            options={'ordering': ['-date_update']},
        ),
        migrations.AlterField(
            model_name='bugzilla',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('info', 'Info')], max_length=15),
        ),
    ]
