# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('family', models.CharField(choices=[('file', 'File'), ('cmd', 'Sys command'), ('stat', 'Stats')], max_length=10)),
                ('path', models.FilePathField(blank=True, null=True)),
                ('command', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CollectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollectProfileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.CollectItem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.CollectProfile')),
            ],
        ),
        migrations.AddField(
            model_name='collectprofile',
            name='collect_items',
            field=models.ManyToManyField(through='collect.CollectProfileItem', to='collect.CollectItem'),
        ),
    ]
