# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectitem',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
