# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20170208_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectitem',
            name='script',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectitem',
            name='family',
            field=models.CharField(choices=[('file', 'File'), ('script', 'Complex script'), ('cmd', 'Sys command'), ('stat', 'Stats')], max_length=10),
        ),
    ]
