# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 20:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='data_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='data_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
