# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_auto_20170212_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectprofile',
            name='collect_items',
        ),
        migrations.RemoveField(
            model_name='collectprofileitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='collectprofileitem',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CollectProfile',
        ),
        migrations.DeleteModel(
            name='CollectProfileItem',
        ),
    ]
