# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_auto_20170213_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('collect_items', models.ManyToManyField(to='collect.CollectItem')),
            ],
        ),
    ]
