# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_collectprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectprofile',
            name='collect_items',
            field=models.ManyToManyField(blank=True, to='collect.CollectItem'),
        ),
    ]
