# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170205_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date_update']},
        ),
    ]
