# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
    ]
