# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20170216_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__parent__name']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
    ]
