# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20170217_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
