# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20170217_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-date']},
        ),
    ]
