# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20170218_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
