# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_notes_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='notes',
            name='uploaded_files',
            field=models.ManyToManyField(blank=True, to='notes.NotesFile'),
        ),
    ]
