# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20170409_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='community',
            name='community_users',
            field=models.ManyToManyField(blank=True, related_name='contributors', through='notes.CommunityUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
