# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20170409_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.Community'),
            preserve_default=False,
        ),
    ]
