# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_auto_20170411_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Community'),
        ),
    ]
