# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_auto_20170411_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('info', 'Info')], default='draft', max_length=15),
        ),
    ]
