# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0028_auto_20170413_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesfile',
            name='original_name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
