# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc_sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
