# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_sport', '0002_auto_20170201_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='personne',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='temps',
        ),
        migrations.AddField(
            model_name='exercice',
            name='temps_db',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='temps_qt',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
