# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_sport', '0003_auto_20170201_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
