# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_sport', '0013_auto_20170201_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercice',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='exercice',
            name='exercice',
            field=models.CharField(choices=[('ventre', 'Ventre'), ('cote_gauche', 'cote gauche'), ('cote_droit', 'cote droit')], max_length=20),
        ),
    ]
