# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_application_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nb_ram', models.IntegerField()),
                ('nb_cpu', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('date_check', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=20)),
                ('ip_public', models.GenericIPAddressField()),
                ('mac_public', models.CharField(max_length=21)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
