# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='state',
            field=models.CharField(choices=[('UN', 'Unknown'), ('KO', 'KO'), ('OK', 'OK')], default='UN', max_length=2),
        ),
    ]
