# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20170114_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nb_ram', models.IntegerField()),
                ('nb_cpu', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('date_check', models.DateField(auto_now=True)),
                ('state', models.CharField(choices=[('UN', 'Unknown'), ('KO', 'KO'), ('OK', 'OK')], default='UN', max_length=2)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeParams',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapping.Node')),
                ('ip_public', models.GenericIPAddressField(null=True)),
                ('ip_admin', models.GenericIPAddressField()),
            ],
            options={
                'abstract': False,
            },
            bases=('mapping.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Application'),
        ),
    ]
