# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20170115_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Host'),
        ),
    ]
