# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_node_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='date_check',
        ),
        migrations.RemoveField(
            model_name='node',
            name='date_check',
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='date_check',
            field=models.DateField(auto_now=True),
        ),
    ]
