# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_nodeparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='state',
        ),
        migrations.RemoveField(
            model_name='node',
            name='state',
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='state',
            field=models.CharField(choices=[('UN', 'Unknown'), ('KO', 'KO'), ('OK', 'OK')], default='UN', max_length=2),
        ),
    ]
