# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_auto_20170115_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeparams',
            name='date_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
