# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0011_auto_20170115_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='disk_size',
        ),
        migrations.RemoveField(
            model_name='node',
            name='nb_cpu',
        ),
        migrations.RemoveField(
            model_name='node',
            name='nb_ram',
        ),
        migrations.RemoveField(
            model_name='node',
            name='os',
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='disk_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='nb_cpu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='nb_ram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
