# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0012_auto_20170116_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeparams',
            options={'ordering': ['-date_check']},
        ),
        migrations.AlterField(
            model_name='host',
            name='nb_cpu',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='nb_ram',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nodeparams',
            name='ip_public',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
