# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0013_auto_20170117_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeparams',
            name='foreman_status_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
