# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0014_nodeparams_foreman_status_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeparams',
            options={'ordering': ['-date_check_foreman']},
        ),
        migrations.RenameField(
            model_name='nodeparams',
            old_name='date_check',
            new_name='date_check_foreman',
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='date_update_foreman',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
