# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_auto_20170117_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeparams',
            name='date_update_foreman',
            field=models.DateTimeField(),
        ),
    ]
