# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0018_host_munin_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='munin_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Munin'),
        ),
    ]
