# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0019_auto_20170120_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Network_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(max_length=12)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Network')),
                ('node_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.NodeParams')),
            ],
        ),
        migrations.AddField(
            model_name='nodeparams',
            name='network_links',
            field=models.ManyToManyField(through='mapping.Network_link', to='mapping.Network'),
        ),
    ]
