# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0020_auto_20170121_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Network_link',
            new_name='NetworkLink',
        ),
    ]
