# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0021_auto_20170121_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeparams',
            name='nb_nics',
            field=models.IntegerField(default=0),
        ),
    ]
