# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_nodeparams_nb_nics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklink',
            name='mac',
            field=models.CharField(max_length=20),
        ),
    ]
