# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0023_auto_20170122_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='iface',
            field=models.CharField(default='', max_length=20),
        ),
    ]
