# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0024_networklink_iface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networklink',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networklink',
            name='node_params',
        ),
        migrations.RemoveField(
            model_name='nodeparams',
            name='network_links',
        ),
        migrations.RemoveField(
            model_name='nodeparams',
            name='node',
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['-date_check_foreman']},
        ),
        migrations.AddField(
            model_name='node',
            name='date_check_foreman',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='node',
            name='date_update_foreman',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='node',
            name='disk_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='foreman_status_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ip_admin',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ip_public',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='nb_cpu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='nb_nics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='nb_ram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='state',
            field=models.CharField(choices=[('UN', 'Unknown'), ('KO', 'KO'), ('OK', 'OK')], default='UN', max_length=2),
        ),
        migrations.DeleteModel(
            name='NetworkLink',
        ),
        migrations.DeleteModel(
            name='NodeParams',
        ),
    ]
