# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0025_auto_20170122_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(max_length=20)),
                ('iface', models.CharField(default='', max_length=20)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Network')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='network_links',
            field=models.ManyToManyField(through='mapping.NetworkLink', to='mapping.Network'),
        ),
    ]
