# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_auto_20170126_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='nic_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
