# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0027_networklink_nic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('servername', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(null=True)),
                ('family', models.CharField(choices=[('apache', 'apache')], default='apache', max_length=20)),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=20)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name']},
        ),
    ]
