# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0029_servicewebserver_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Application')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='active',
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='application',
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicewebserver',
            name='node',
        ),
        migrations.AddField(
            model_name='servicewebserver',
            name='service_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapping.Service'),
            preserve_default=False,
        ),
    ]
