# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0030_auto_20170127_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReverseProxy',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapping.Service')),
                ('servername', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(null=True)),
                ('proxy_url', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(choices=[('apache', 'apache')], default='apache', max_length=20)),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=20)),
            ],
            bases=('mapping.service',),
        ),
    ]
