# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0031_servicereverseproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicewebserver',
            name='reverse_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.ServiceReverseProxy'),
        ),
    ]
