# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0032_servicewebserver_reverse_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereverseproxy',
            name='servername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
