# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0036_auto_20170129_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='disk_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='munin_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Munin'),
        ),
        migrations.AlterField(
            model_name='node',
            name='nb_cpu',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='nb_ram',
            field=models.BigIntegerField(),
        ),
    ]
