# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0038_node_collect_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='collect_profile',
        ),
    ]
