# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_auto_20170213_1455'),
        ('mapping', '0039_remove_node_collect_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='collect_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collect.CollectProfile'),
        ),
    ]
