# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0041_node_is_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDataBase',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapping.Service')),
                ('family', models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], default='postgres', max_length=20)),
                ('dbname', models.CharField(max_length=50)),
            ],
            bases=('mapping.service',),
        ),
    ]
