# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0042_servicedatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapping.Application'),
            preserve_default=False,
        ),
    ]
