# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0043_auto_20170306_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='node',
            name='managed_by_heimdall',
            field=models.BooleanField(default=False),
        ),
    ]
