# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0044_auto_20170312_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='network_links',
            field=models.ManyToManyField(blank=True, through='mapping.NetworkLink', to='mapping.Network'),
        ),
    ]
