# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0045_auto_20170312_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklink',
            name='iface',
            field=models.CharField(blank=True, default='ens', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='nic_type',
            field=models.CharField(blank=True, default='virtio', max_length=20, null=True),
        ),
    ]
