# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0046_auto_20170313_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicewebserver',
            name='reverse_proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.ServiceReverseProxy'),
        ),
    ]
