# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0016_auto_20170117_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=5)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Node')),
            ],
        ),
    ]
