# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_auto_20170117_1722'),
        ('monitoring', '0002_auto_20170120_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='munin',
            name='node',
        ),
        migrations.AddField(
            model_name='munin',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Node'),
        ),
    ]
